# Generated by Django 5.2.10 on 2026-03-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
